#pragma once
#define NOMINMAX
#include <stdio.h>
#include <winsock2.h>
#include <Windows.h>
#include <process.h>
#include <conio.h>
#include "string.h"
#include <dshow.h>
#include <iostream>
#include <opencv2/core/core.hpp>
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include <opencv2/videoio.hpp>
#include <opencv2/core/ocl.hpp>
#include <wx/wx.h>
#include <wx/dcbuffer.h>
#include <wx/event.h>
#include <wx/crt.h>
#include <wx/textctrl.h>
#include "easylogging.h"
#include "id.h"
#include <wx/textfile.h>
#include <wx/arrstr.h> 
#include <map>
#include <functional>
#include <cstdio>
#include <iomanip>
#include <ctime>
